"use client";

import { useEffect, useState } from "react";

type Player = {
  id: string;
    playerId: string;
      inGameName: string;
        role: string;

          heroPower: {
              from: string;
                  to: string;
                      growth: string;
                        };

                          firstSquadPower: {
                              from: string;
                                  to: string;
                                      growth: string;
                                        };

                                          firstSquadType: string;
                                          };

                                          type Response = {
                                            fromWeek: number;
                                              toWeek: number;
                                                totalPlayers: number;
                                                  players: Player[];
                                                  };

                                                  export default function CompareReportsPage() {
                                                    const [fromWeek, setFromWeek] = useState(1);
                                                      const [toWeek, setToWeek] = useState(2);

                                                        const [data, setData] = useState<Response | null>(null);
                                                          const [loading, setLoading] = useState(false);

                                                            useEffect(() => {
                                                                loadComparison();
                                                                  }, []);

                                                                    async function loadComparison() {
                                                                        setLoading(true);

                                                                            try {
                                                                                  const res = await fetch(
                                                                                          `/api/admin/reports/compare?from=${fromWeek}&to=${toWeek}`
                                                                                                );

                                                                                                      const json = await res.json();

                                                                                                            setData(json);
                                                                                                                } catch (err) {
                                                                                                                      console.error(err);
                                                                                                                          } finally {
                                                                                                                                setLoading(false);
                                                                                                                                    }
                                                                                                                                      }

                                                                                                                                        return (
                                                                                                                                            <main className="min-h-screen bg-[#050816] text-white p-8">

                                                                                                                                                  <h1 className="text-4xl font-bold text-blue-400 mb-8">
                                                                                                                                                          Compare Reports
                                                                                                                                                                </h1>

                                                                                                                                                                      <div className="rounded-xl border border-blue-800 bg-[#0b1024] p-6 mb-8">

                                                                                                                                                                              <div className="flex flex-wrap gap-4 items-end">

                                                                                                                                                                                        <div>
                                                                                                                                                                                                    <label className="block text-gray-400 mb-2">
                                                                                                                                                                                                                  From Week
                                                                                                                                                                                                                              </label>

                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                        type="number"
                                                                                                                                                                                                                                                                      min={1}
                                                                                                                                                                                                                                                                                    value={fromWeek}
                                                                                                                                                                                                                                                                                                  onChange={(e) =>
                                                                                                                                                                                                                                                                                                                  setFromWeek(Number(e.target.value))
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                              className="rounded bg-[#050816] border border-blue-700 px-3 py-2"
                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                          <label className="block text-gray-400 mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                        To Week
                                                                                                                                                                                                                                                                                                                                                                                                                    </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                                              type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                            min={1}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={toWeek}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setToWeek(Number(e.target.value))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="rounded bg-[#050816] border border-blue-700 px-3 py-2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={loadComparison}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="rounded bg-blue-600 hover:bg-blue-700 px-6 py-2 font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Compare
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {loading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-gray-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Loading...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="overflow-x-auto rounded-xl border border-blue-800">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <table className="w-full">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <thead className="bg-[#111827]">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <th className="p-4 text-left">Player</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <th className="p-4 text-left">Hero Growth</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <th className="p-4 text-left">Squad Growth</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <th className="p-4 text-left">Squad Type</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </tr>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </thead>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <tbody>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {data?.players.map((player) => (

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <tr
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  key={player.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="border-t border-blue-900"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td className="p-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {player.inGameName}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </td>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td className="p-4 text-green-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  +{player.heroPower.growth}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </td>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td className="p-4 text-green-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          +{player.firstSquadPower.growth}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </td>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td className="p-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {player.firstSquadType}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </tr>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </tbody>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </table>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }