"use client";

type Role = "ALL" | "OWNER" | "R5" | "R4" | "MEMBER";
type Status = "ALL" | "SUBMITTED" | "MISSING";

type FilterModalProps = {
  open: boolean;
    role: Role;
      status: Status;
        onRoleChange: (role: Role) => void;
          onStatusChange: (status: Status) => void;
            onApply: () => void;
              onClear: () => void;
                onClose: () => void;
                };

                export default function FilterModal({
                  open,
                    role,
                      status,
                        onRoleChange,
                          onStatusChange,
                            onApply,
                              onClear,
                                onClose,
                                }: FilterModalProps) {
                                  if (!open) return null;

                                    return (
                                        <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/60">
                                              <div className="w-full max-w-md rounded-t-3xl bg-[#0b1024] p-6">

                                                      <h2 className="mb-6 text-2xl font-bold text-white">
                                                                Filters
                                                                        </h2>

                                                                                <div className="mb-6">
                                                                                          <label className="mb-2 block text-sm text-gray-400">
                                                                                                      Role
                                                                                                                </label>

                                                                                                                          <select
                                                                                                                                      value={role}
                                                                                                                                                  onChange={(e) => onRoleChange(e.target.value as Role)}
                                                                                                                                                              className="w-full rounded-xl border border-gray-700 bg-[#050816] px-4 py-3 text-white"
                                                                                                                                                                        >
                                                                                                                                                                                    <option value="ALL">All Roles</option>
                                                                                                                                                                                                <option value="OWNER">OWNER</option>
                                                                                                                                                                                                            <option value="R5">R5</option>
                                                                                                                                                                                                                        <option value="R4">R4</option>
                                                                                                                                                                                                                                    <option value="MEMBER">MEMBER</option>
                                                                                                                                                                                                                                              </select>
                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                              <div className="mb-8">
                                                                                                                                                                                                                                                                        <label className="mb-2 block text-sm text-gray-400">
                                                                                                                                                                                                                                                                                    Status
                                                                                                                                                                                                                                                                                              </label>

                                                                                                                                                                                                                                                                                                        <select
                                                                                                                                                                                                                                                                                                                    value={status}
                                                                                                                                                                                                                                                                                                                                onChange={(e) => onStatusChange(e.target.value as Status)}
                                                                                                                                                                                                                                                                                                                                            className="w-full rounded-xl border border-gray-700 bg-[#050816] px-4 py-3 text-white"
                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                  <option value="ALL">All</option>
                                                                                                                                                                                                                                                                                                                                                                              <option value="SUBMITTED">Submitted</option>
                                                                                                                                                                                                                                                                                                                                                                                          <option value="MISSING">Missing</option>
                                                                                                                                                                                                                                                                                                                                                                                                    </select>
                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="grid grid-cols-3 gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={onClear}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="rounded-xl bg-gray-700 py-3 font-semibold text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Clear
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={onClose}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="rounded-xl bg-red-600 py-3 font-semibold text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Cancel
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={onApply}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="rounded-xl bg-blue-600 py-3 font-semibold text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Apply
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }