import Link from "next/link";

type PlayerCardProps = {
  id: string;
    playerId: string;
      inGameName: string;
        role: string;
          heroPower: string | null;
            firstSquadPower: string | null;
              firstSquadType: string | null;
                totalReports: number;
                  submittedCurrentWeek: boolean;
                    lastReportDate: string | null;
                    };

                    export default function PlayerCard({
                      playerId,
                        inGameName,
                          role,
                            heroPower,
                              firstSquadPower,
                                firstSquadType,
                                  totalReports,
                                    submittedCurrentWeek,
                                      lastReportDate,
                                      }: PlayerCardProps) {
                                        return (
                                            <Link href={`/admin/reports/${playerId}`}>
                                                  <div
                                                          className={`
                                                                    rounded-xl
                                                                              p-6
                                                                                        bg-[#0b1024]
                                                                                                  transition-all
                                                                                                            duration-300
                                                                                                                      hover:scale-[1.02]
                                                                                                                                hover:shadow-xl
                                                                                                                                          cursor-pointer
                                                                                                                                                    ${
                                                                                                                                                                submittedCurrentWeek
                                                                                                                                                                              ? "border border-green-600 hover:border-green-400"
                                                                                                                                                                                            : "border border-red-600 hover:border-red-400"
                                                                                                                                                                                                      }
                                                                                                                                                                                                              `}
                                                                                                                                                                                                                    >
                                                                                                                                                                                                                            <div className="flex items-center justify-between mb-5">
                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                  <h2 className="text-xl font-bold text-white">
                                                                                                                                                                                                                                                                {inGameName}
                                                                                                                                                                                                                                                                            </h2>

                                                                                                                                                                                                                                                                                        <p className="text-sm text-gray-400">
                                                                                                                                                                                                                                                                                                      {playerId}
                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                      <span className="rounded-lg bg-blue-700 px-3 py-1 text-sm font-semibold">
                                                                                                                                                                                                                                                                                                                                                  {role}
                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                            <div className="space-y-2 text-sm">

                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-gray-400">
                                                                                                                                                                                                                                                                                                                                                                                                                Hero Power
                                                                                                                                                                                                                                                                                                                                                                                                                            </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      {heroPower ?? "-"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-gray-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Squad Power
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {firstSquadPower ?? "-"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-gray-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Squad Type
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {firstSquadType ?? "-"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-gray-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Reports
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {totalReports}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-gray-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Last Report
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {lastReportDate
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ? new Date(lastReportDate).toLocaleDateString()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      : "-"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="mt-6">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className={`rounded-lg py-2 text-center font-semibold ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                submittedCurrentWeek
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ? "bg-green-600"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : "bg-red-600"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {submittedCurrentWeek
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ? "Submitted"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              : "Missing"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }