"use client";

type SortOption =
  | "NAME_ASC"
    | "NAME_DESC"
      | "ROLE_HIGH"
        | "ROLE_LOW";

        type SortModalProps = {
          open: boolean;
            value: SortOption;
              onChange: (value: SortOption) => void;
                onApply: () => void;
                  onClear: () => void;
                    onClose: () => void;
                    };

                    export default function SortModal({
                      open,
                        value,
                          onChange,
                            onApply,
                              onClear,
                                onClose,
                                }: SortModalProps) {
                                  if (!open) return null;

                                    return (
                                        <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/60">
                                              <div className="w-full max-w-md rounded-t-3xl bg-[#0b1024] p-6">

                                                      <h2 className="mb-6 text-2xl font-bold text-white">
                                                                Sort Players
                                                                        </h2>

                                                                                <div className="space-y-3">

                                                                                          <label className="flex items-center gap-3 rounded-xl border border-gray-700 p-3">
                                                                                                      <input
                                                                                                                    type="radio"
                                                                                                                                  checked={value === "NAME_ASC"}
                                                                                                                                                onChange={() => onChange("NAME_ASC")}
                                                                                                                                                            />
                                                                                                                                                                        <span className="text-white">Name (A → Z)</span>
                                                                                                                                                                                  </label>

                                                                                                                                                                                            <label className="flex items-center gap-3 rounded-xl border border-gray-700 p-3">
                                                                                                                                                                                                        <input
                                                                                                                                                                                                                      type="radio"
                                                                                                                                                                                                                                    checked={value === "NAME_DESC"}
                                                                                                                                                                                                                                                  onChange={() => onChange("NAME_DESC")}
                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                          <span className="text-white">Name (Z → A)</span>
                                                                                                                                                                                                                                                                                    </label>

                                                                                                                                                                                                                                                                                              <label className="flex items-center gap-3 rounded-xl border border-gray-700 p-3">
                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                        type="radio"
                                                                                                                                                                                                                                                                                                                                      checked={value === "ROLE_HIGH"}
                                                                                                                                                                                                                                                                                                                                                    onChange={() => onChange("ROLE_HIGH")}
                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                            <span className="text-white">Role (OWNER → MEMBER)</span>
                                                                                                                                                                                                                                                                                                                                                                                      </label>

                                                                                                                                                                                                                                                                                                                                                                                                <label className="flex items-center gap-3 rounded-xl border border-gray-700 p-3">
                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                          type="radio"
                                                                                                                                                                                                                                                                                                                                                                                                                                        checked={value === "ROLE_LOW"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={() => onChange("ROLE_LOW")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-white">Role (MEMBER → OWNER)</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="mt-8 grid grid-cols-3 gap-3">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={onClear}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="rounded-xl bg-gray-700 py-3 font-semibold text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Clear
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={onClose}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="rounded-xl bg-red-600 py-3 font-semibold text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Cancel
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={onApply}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="rounded-xl bg-blue-600 py-3 font-semibold text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Apply
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }