"use client";

type Props = {
  open: boolean;
    canEdit: boolean;
      report: {
          heroPower: string;
              firstSquadPower: string;
                  firstSquadType: string;
                      createdAt: string;
                        } | null;
                          onClose: () => void;
                            onEdit: () => void;
                            };

                            export default function ReportSubmittedModal({
                              open,
                                canEdit,
                                  report,
                                    onClose,
                                      onEdit,
                                      }: Props) {
                                        if (!open || !report) return null;

                                          return (
                                              <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4">

                                                    <div className="w-full max-w-md rounded-2xl border border-blue-800 bg-[#0b1024] p-6 shadow-2xl">

                                                            <div className="text-center">

                                                                      <div className="text-6xl mb-3">
                                                                                  ✅
                                                                                            </div>

                                                                                                      <h2 className="text-2xl font-bold text-blue-400">
                                                                                                                  Weekly Report Submitted
                                                                                                                            </h2>

                                                                                                                                      <p className="mt-2 text-gray-400">
                                                                                                                                                  Your report has already been submitted.
                                                                                                                                                            </p>

                                                                                                                                                                    </div>

                                                                                                                                                                            <div className="mt-8 space-y-4">

                                                                                                                                                                                      <div className="rounded-xl bg-[#050816] p-4">
                                                                                                                                                                                                  <p className="text-sm text-gray-400">
                                                                                                                                                                                                                Hero Power
                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                        <p className="mt-1 text-xl font-bold">
                                                                                                                                                                                                                                                      {Number(report.heroPower).toLocaleString()}
                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                      <div className="rounded-xl bg-[#050816] p-4">
                                                                                                                                                                                                                                                                                                  <p className="text-sm text-gray-400">
                                                                                                                                                                                                                                                                                                                First Squad Power
                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                        <p className="mt-1 text-xl font-bold">
                                                                                                                                                                                                                                                                                                                                                      {Number(report.firstSquadPower).toLocaleString()}
                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                      <div className="rounded-xl bg-[#050816] p-4">
                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-sm text-gray-400">
                                                                                                                                                                                                                                                                                                                                                                                                                Squad Type
                                                                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="mt-1 text-xl font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      {report.firstSquadType}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="rounded-xl bg-[#050816] p-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-sm text-gray-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Submitted
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="mt-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {new Date(report.createdAt).toLocaleString()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="mt-8 flex gap-3">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={onClose}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="flex-1 rounded-xl border border-blue-700 py-3 font-semibold hover:bg-blue-900/20"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Close
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    disabled={!canEdit}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={onEdit}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="flex-1 rounded-xl bg-blue-600 py-3 font-semibold disabled:cursor-not-allowed disabled:opacity-50 hover:bg-blue-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {canEdit ? "Edit Report" : "Editing Closed"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }